version: "3.1"

services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
     - '5432:5432'
    volumes:
      - ./server/data/entrypoint:/docker-entrypoint-initdb.d/
      - ./server/data/database:/var/lib/postgresql/data

